### PR TITLE
ds: Clean up joystick-related stuff

### PR DESCRIPTION
**Pull request by auscompgeek**

### CODE REVIEW

**Comment by auscompgeek** [comment]
Not sure what the best approach for that type cast linter warning is.

**Comment by Lytigas** [comment]
Is there any official guidance on whether to use `Result` or `Option` for these simple erroring cases? The best I could find was a reddit post quoting docs (that seem to no longer exist) arguing `Result` is preferrable if the scenario is an "error." I do see the case for less to type with `Option`, and also one could argue there isn't an "error" but a "search" for a button that finds nothing. I guess I'm OK with using `Option`

With regards to the typecast, just using `i32::from` seems fine to me. I doubt types will change though, so it doesn't matter really. Also, `JoystickError` is now dead code and should be removed.

**Comment by auscompgeek** [comment]
The previous contract said that these could return _any_ JoystickError, which is objectively worse for ergonomics when it is simply either valid or invalid. You can use `?` on an Option anyway.

> With regards to the typecast, just using `i32::from` seems fine to me.

`i32::from` isn't a const fn.

**Comment by auscompgeek** [comment]
That said, maybe it might be better to have the stick getters return a Result with a singleton error.

**Comment by auscompgeek** [comment]
I've come up with a better idea for the stick getters. We'll have new methods that return newtypes around the HAL joystick structs, and a get method on those that return an Option (with the semantics being "the thing you asked for is missing").

**Comment by auscompgeek** [comment]
Throwing in the common axes as associated constants so teams don't have to construct them themselves.

Also, people like gamepads, so throwing in XInput constants as well.

**Comment by auscompgeek** [comment]
Ok I'm done here. Here's a way you could wrap around this functionality for convenience:

```rust
struct Joystick<'a> {
  ds: &'a DriverStation,
  port: JoystickPort,
  prev_buttons: JoystickButtons,
  curr_buttons: JoystickButtons,
  buttons_pressed: u32,
}
impl Joystick<'_> {
  fn read_buttons(&mut self) {
    let buttons = self.ds.stick_buttons(self.port);
    self.prev_buttons = self.curr_buttons;
    self.curr_buttons = buttons;
    self.buttons_pressed |= buttons.pressed_since(self.prev_buttons).bits();
  }
  fn buttons(&self) -> JoystickButtons {
    self.curr_buttons
  }
  fn axes(&self) -> JoystickAxes {
    self.ds.stick_axes(self.port)
  }
  fn pov(&self) -> Option<i16> {
    self.ds.stick_povs(self.port).first()
  }
}
```

To correctly track button presses, you'd have to call `read_buttons` whenever a DS packet arrives (so if a team is using `start_timed` they'd have to spawn another thread to wait for DS data).

**Comment by Lytigas** [comment]
I like these changes. I'd also like to remove the lifetime from `DriverStation` at some point, but that's another PR.

**Pull request merged**
